name: Daily Data Cleaning
on:
  schedule:
    - cron: '0 2 * * *'
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pandas numpy
      - name: Run Master Pipeline
        run: python src/master_pipeline.py
